version: 2

build:
  image: latest
  apt_packages:
    - gcc-10
    - g++-10
    - cmake

sphinx:
  configuration: docs/sphinx_docs/conf.py

formats: all
python:
  version: "3.8"
  install:
    - requirements: docs/sphinx_docs/requirements.txt
    - method: pip
      path: .
  system_packages: true

submodules:
  include: all
