name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - sparse-blossom-remove-skbuild

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.6", "3.9"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add requirements
        run: python -m pip install --upgrade wheel setuptools cmake>=3.12 ninja

      - name: Build and install
        run: pip install --verbose -e .

      - name: Test
        run: python -m pytest src/pymatching
