name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - sparse-blossom-remove-skbuild
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    sdk: "0.0.22000.194"
    vsversion: "16.7"
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.15"
      CIBW_BUILD: "cp3*-*"
      CIBW_SKIP: "*-win32"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: ilammy/msvc-dev-cmd@v1

    - uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_ARCHS_MACOS: auto universal2

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl

